# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_data.core.ipynb (unless otherwise specified).

__all__ = ['pct_splits']

# Cell
from fastai2.basics import *

# Cell
def pct_splits(splits, pct=1.0):
    ''' returns pct of splits[0] and pct of splits[1]
    splits: ([], []) '''
    train_split, val_split = splits
    new_train_split = train_split[:int(len(train_split)*pct)]
    new_val_split = val_split[:int(len(val_split)*pct)]
    return new_train_split, new_val_split