# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pct_splits": "01_data.core.ipynb",
         "gen_key_padding_mask": "02_pytorch.transformer.ipynb",
         "gen_lm_mask": "02_pytorch.transformer.ipynb",
         "BatchFirstTransformerEncoder": "02_pytorch.transformer.ipynb",
         "BatchFirstTransformerDecoder": "02_pytorch.transformer.ipynb",
         "BatchFirstMultiheadAttention": "02_pytorch.transformer.ipynb",
         "CrossAttention": "02_pytorch.transformer.ipynb",
         "check_requires_grad": "03_pytorch.model.ipynb",
         "set_requires_grad": "03_pytorch.model.ipynb",
         "freeze_to": "03_pytorch.model.ipynb",
         "get_latest_metric_val": "04_optuna.ipynb",
         "OptunaPruningCallback": "04_optuna.ipynb"}

modules = ["data/core.py",
           "pytorch/transformer.py",
           "pytorch/model.py",
           "optuna.py"]

doc_url = "https://cwza.github.io/fastai2_utils/"

git_url = "https://github.com/cwza/fastai2_utils/tree/master/"

def custom_doc_links(name): return None
